### ISSUE TITLE
Difference between this and postcss-icss-values?

### ISSUE THREAD

**Issue by joepie91** [css-modules/postcss-modules-values#6]
There seems to be a different project under the same organization that appears to be doing the exact same thing: https://github.com/css-modules/postcss-icss-values. Both seem to be developed independently of one another, by different people.

What's the difference between these two libraries, and when should which be used?

**Comment by evilebottnawi** [comment]
Sorry for delay, it is other implementation of Interpolate CSS, but looks it was deprecated and abadoned
